openapi: 3.0.0
info:
  version: "1"
  title: MIS API
servers:
  - url: http://127.0.0.1:8000
    description: Development
  - url: http://production.com:80
    description: Production

x-tagGroups:
  - name: Авторизация
    tags:
      - Логин
  - name: Консультации
    tags:
      - Консультация
  - name: Докторы
    tags:
      - Доктор

paths:
  # Auth
  /api/v1/auth:
    $ref: "api/v1/auth/login.yaml"

  /api/v1/auth/refresh:
    $ref: "api/v1/auth/refresh.yaml"

  # Consultations
  /api/v1/consultations:
    $ref: "api/v1/consultations/get_consultations.yaml"

  /api/v1/consultations/{id}/status:
    $ref: "api/v1/consultations/update_consultation_status.yaml"

  # Doctor
  /api/v1/doctors/{id}/add_clinic:
    $ref: "api/v1/doctors/add_clinic.yaml"

securitySchemes:
  Bearer:
    type: http
    scheme: bearer
    bearerFormat: JWT
